#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${SSH_TARGET:-}" ]]; then
  echo "Usage: SSH_TARGET=user@host [REMOTE_DIR=lodia] [LODIA_WEB_PORT=18080] [LODIA_BIND_HOST=127.0.0.1] scripts/deploy-aliyun-safe.sh" >&2
  exit 2
fi

REMOTE_DIR="${REMOTE_DIR:-lodia}"
LODIA_WEB_PORT="${LODIA_WEB_PORT:-18080}"
LODIA_BIND_HOST="${LODIA_BIND_HOST:-127.0.0.1}"
PROJECT_NAME="${PROJECT_NAME:-lodia_prod}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')}"
LODIA_ADMIN_TOKEN="${LODIA_ADMIN_TOKEN:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')}"
LODIA_REVIEWER_TOKEN="${LODIA_REVIEWER_TOKEN:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')}"
LODIA_CONTRIBUTOR_TOKEN="${LODIA_CONTRIBUTOR_TOKEN:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')}"
LODIA_PASSWORD_PEPPER="${LODIA_PASSWORD_PEPPER:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')}"
LODIA_REQUEST_SIGNATURE_SECRET="${LODIA_REQUEST_SIGNATURE_SECRET:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')}"
LODIA_ASYNC_PROCESSING="${LODIA_ASYNC_PROCESSING:-true}"
REDIS_URL="${REDIS_URL:-redis://redis:6379/0}"
LODIA_QUEUE_BACKEND="${LODIA_QUEUE_BACKEND:-redis}"
LODIA_RAW_OBJECT_TTL_HOURS="${LODIA_RAW_OBJECT_TTL_HOURS:-24}"
LODIA_DB_POOL_MIN_SIZE="${LODIA_DB_POOL_MIN_SIZE:-1}"
LODIA_DB_POOL_MAX_SIZE="${LODIA_DB_POOL_MAX_SIZE:-10}"
LODIA_MAX_ASSET_BYTES="${LODIA_MAX_ASSET_BYTES:-1048576}"
LODIA_UPLOAD_SESSION_TTL_SECONDS="${LODIA_UPLOAD_SESSION_TTL_SECONDS:-900}"
LODIA_MAX_REQUEST_BODY_BYTES="${LODIA_MAX_REQUEST_BODY_BYTES:-1048576}"
LODIA_RATE_LIMIT_ENABLED="${LODIA_RATE_LIMIT_ENABLED:-true}"
LODIA_RATE_LIMIT_REQUESTS="${LODIA_RATE_LIMIT_REQUESTS:-120}"
LODIA_RATE_LIMIT_WINDOW_SECONDS="${LODIA_RATE_LIMIT_WINDOW_SECONDS:-60}"
LODIA_TRUST_PROXY_HEADERS="${LODIA_TRUST_PROXY_HEADERS:-false}"
LODIA_REQUIRE_REQUEST_SIGNATURE="${LODIA_REQUIRE_REQUEST_SIGNATURE:-false}"
LODIA_MAX_PAGE_LIMIT="${LODIA_MAX_PAGE_LIMIT:-500}"
LODIA_DATASET_MAX_CASES="${LODIA_DATASET_MAX_CASES:-5000}"
LODIA_OBJECT_STORAGE_BACKEND="${LODIA_OBJECT_STORAGE_BACKEND:-local}"
LODIA_OBJECT_STORAGE_DIR="${LODIA_OBJECT_STORAGE_DIR:-/objects}"
LODIA_S3_SSE_ALGORITHM="${LODIA_S3_SSE_ALGORITHM:-AES256}"
LODIA_S3_KMS_KEY_ID="${LODIA_S3_KMS_KEY_ID:-}"

if ! command -v rsync >/dev/null 2>&1; then
  echo "rsync is required locally." >&2
  exit 2
fi

ENV_FILE="$(mktemp)"
trap 'rm -f "$ENV_FILE"' EXIT
cat > "$ENV_FILE" <<EOF
LODIA_BIND_HOST=${LODIA_BIND_HOST}
LODIA_WEB_PORT=${LODIA_WEB_PORT}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
LODIA_ADMIN_TOKEN=${LODIA_ADMIN_TOKEN}
LODIA_REVIEWER_TOKEN=${LODIA_REVIEWER_TOKEN}
LODIA_CONTRIBUTOR_TOKEN=${LODIA_CONTRIBUTOR_TOKEN}
LODIA_PASSWORD_PEPPER=${LODIA_PASSWORD_PEPPER}
LODIA_REQUEST_SIGNATURE_SECRET=${LODIA_REQUEST_SIGNATURE_SECRET}
LODIA_ASYNC_PROCESSING=${LODIA_ASYNC_PROCESSING}
REDIS_URL=${REDIS_URL}
LODIA_QUEUE_BACKEND=${LODIA_QUEUE_BACKEND}
LODIA_RAW_OBJECT_TTL_HOURS=${LODIA_RAW_OBJECT_TTL_HOURS}
LODIA_DB_POOL_MIN_SIZE=${LODIA_DB_POOL_MIN_SIZE}
LODIA_DB_POOL_MAX_SIZE=${LODIA_DB_POOL_MAX_SIZE}
LODIA_MAX_ASSET_BYTES=${LODIA_MAX_ASSET_BYTES}
LODIA_UPLOAD_SESSION_TTL_SECONDS=${LODIA_UPLOAD_SESSION_TTL_SECONDS}
LODIA_MAX_REQUEST_BODY_BYTES=${LODIA_MAX_REQUEST_BODY_BYTES}
LODIA_RATE_LIMIT_ENABLED=${LODIA_RATE_LIMIT_ENABLED}
LODIA_RATE_LIMIT_REQUESTS=${LODIA_RATE_LIMIT_REQUESTS}
LODIA_RATE_LIMIT_WINDOW_SECONDS=${LODIA_RATE_LIMIT_WINDOW_SECONDS}
LODIA_TRUST_PROXY_HEADERS=${LODIA_TRUST_PROXY_HEADERS}
LODIA_REQUIRE_REQUEST_SIGNATURE=${LODIA_REQUIRE_REQUEST_SIGNATURE}
LODIA_MAX_PAGE_LIMIT=${LODIA_MAX_PAGE_LIMIT}
LODIA_DATASET_MAX_CASES=${LODIA_DATASET_MAX_CASES}
LODIA_OBJECT_STORAGE_BACKEND=${LODIA_OBJECT_STORAGE_BACKEND}
LODIA_OBJECT_STORAGE_DIR=${LODIA_OBJECT_STORAGE_DIR}
LODIA_S3_SSE_ALGORITHM=${LODIA_S3_SSE_ALGORITHM}
LODIA_S3_KMS_KEY_ID=${LODIA_S3_KMS_KEY_ID}
EOF

echo "Preflight on ${SSH_TARGET}..."
ssh "$SSH_TARGET" "set -e
  command -v docker >/dev/null
  docker compose version >/dev/null
  if ss -ltnH | awk '{print \$4}' | grep -Eq '(^|:)${LODIA_WEB_PORT}$'; then
    echo 'Port ${LODIA_WEB_PORT} is already in use. Choose another LODIA_WEB_PORT.' >&2
    exit 20
  fi
  mkdir -p '${REMOTE_DIR}/storage/prod'
"

echo "Syncing project to ${SSH_TARGET}:${REMOTE_DIR}..."
rsync -az --delete \
  --exclude='.git' \
  --exclude='.DS_Store' \
  --exclude='.venv' \
  --exclude='node_modules' \
  --exclude='apps/web/node_modules' \
  --exclude='apps/web/dist' \
  --exclude='storage' \
  --exclude='.env' \
  --exclude='.env.*' \
  ./ "$SSH_TARGET:${REMOTE_DIR}/"
rsync -az "$ENV_FILE" "$SSH_TARGET:${REMOTE_DIR}/.env.production"

echo "Starting isolated Lodia compose project..."
ssh "$SSH_TARGET" "set -e
  cd '${REMOTE_DIR}'
  docker compose -p '${PROJECT_NAME}' --env-file .env.production -f docker-compose.prod.yml up -d --build
  curl -fsS 'http://127.0.0.1:${LODIA_WEB_PORT}/api/ready'
  curl -fsSI 'http://127.0.0.1:${LODIA_WEB_PORT}/' >/dev/null
"

cat <<EOF
Lodia deployed without touching existing reverse proxies or system services.

Remote directory: ${REMOTE_DIR}
Compose project:  ${PROJECT_NAME}
Bind address:     ${LODIA_BIND_HOST}
Port:             ${LODIA_WEB_PORT}
Admin token:      stored in ${REMOTE_DIR}/.env.production

Local verification:
  ssh -L ${LODIA_WEB_PORT}:127.0.0.1:${LODIA_WEB_PORT} ${SSH_TARGET}
  open http://127.0.0.1:${LODIA_WEB_PORT}

If you intentionally want public access, rerun with:
  LODIA_BIND_HOST=0.0.0.0 LODIA_WEB_PORT=${LODIA_WEB_PORT} SSH_TARGET=${SSH_TARGET} scripts/deploy-aliyun-safe.sh
EOF
